### ISSUE TITLE
Table cell column divider option not present.

### ISSUE THREAD

**Issue by Sam4829** [gofynd/nitrozen-react#57]
The JDS component of table cell gives the flexibility to enable and disable column divider, which shows and hides side borders of a table cell.

**Comment by Sam4829** [comment]
![IMG_20230216_122459.png](https://user-images.githubusercontent.com/22861554/219290585-553c67b9-cfac-4c18-a706-22940af21ba7.png)

**Comment by ShahRohan27** [comment]
WIP

**Comment by ShahRohan27** [comment]
Fixed, will be available in the next release

**Comment by ShahRohan27** [comment]
https://github.com/gofynd/nitrozen-react/pull/62
