### ISSUE TITLE
Issue with Date Picker: Clicking the same date twice results in end date being displayed as NaN/NaN/NaN.

### ISSUE THREAD

**Issue by ryadav96** [gofynd/nitrozen-react#80]
![image](https://user-images.githubusercontent.com/30411972/230081810-4467bc17-b9fe-4d2e-9435-f9af259c2e8c.png)

**Comment by bijankundu** [comment]
Fixed in #99

**Comment by ShahRohan27** [comment]
Closing this as this is now fixed
